- name: Set up LAMP server
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure MySQL is installed
      apt:
        name: mysql-server
        state: present

    - name: Ensure PHP is installed
      apt:
        name: php
        state: present

    - name: Ensure PHP-MySQL module is installed
      apt:
        name: php-mysql
        state: present

    - name: Start and enable Apache service
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Copy index.php to web root
      copy:
        content: |
          <?php
          phpinfo();
          ?>
        dest: /var/www/html/index.php
        owner: www-data
        group: www-data" > lamp_setup.yml
